### ISSUE TITLE
While doing prediction facing this error

### ISSUE THREAD

**Issue by ghost** [lyuqin/HydraNet-WikiSQL#11]
input_ids (101072, 96)
input_mask (101072, 96)
segment_ids (101072, 96)
num of samples: 15878
PyTorch model loaded from output/20200207_105347\model_4.pt
model prediction start
Traceback (most recent call last):
  File "wikisql_prediction.py", line 73, in <module>
    model_outputs = model.dataset_inference(pred_data)
  File "C:\Users\mohdf\OneDrive\Desktop\Hydranet_sql\HydraNet-WikiSQL\modeling\base_model.py", line 24, in dataset_inference
    model_outputs = self.model_inference(dataset.model_inputs)
  File "C:\Users\mohdf\OneDrive\Desktop\Hydranet_sql\HydraNet-WikiSQL\modeling\torch_model.py", line 57, in model_inference
    model_output = self.model(**input_tensor)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\OneDrive\Desktop\Hydranet_sql\HydraNet-WikiSQL\modeling\torch_model.py", line 114, in forward
    bert_output, pooled_output = self.base_model(
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 815, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 508, in forward
    layer_outputs = layer_module(
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 395, in forward
    self_attention_outputs = self.attention(
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 323, in forward
    self_outputs = self.self(
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 187, in forward
    mixed_query_layer = self.query(hidden_states)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\mohdf\anaconda3\envs\hydranet2\lib\site-packages\torch\nn\functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**Comment by ghost** [comment]
getting this error while running wikisql_prediction.py

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/19353524/161595308-4e6d46d4-0d7d-4bd8-9918-fe8c808b691d.PNG)

**Comment by lyuqin** [comment]
What's the PyTorch and Transformers versions? Could you test in CPU mode first (CUDA_VISIBLE_DEVICES=-1 python wikisql_prediction.py) and see if any exception?

**Comment by ghost** [comment]
torch              1.10.1
transformers       4.5.0

**Comment by ghost** [comment]
[``](url)
![Screenshot (7)](https://user-images.githubusercontent.com/19353524/161616448-6d2bd21a-a7d4-4ca0-851e-7c6fa2e9a236.png)
how much time it will take on cpu for the prediction

**Comment by lyuqin** [comment]
This is simply a test because it will take super long time on cpu. Now it seems to be some CUDA/GPU issue, could you google a bit to see if any solution?

**Comment by ghost** [comment]
While googling , Suggestion are generally decreasing the batch size. But still getting this error , tried many approaches
but none seems to work

**Comment by lyuqin** [comment]
Could you try with Pytorch==1.7.1? I haven't had this issue from all the user feedbacks before and it's hard to debug from my side without env to reproduce this exception.

**Comment by lyuqin** [comment]
btw, could you try run with docker?
(from readme) _We can also run experiments with docker image: docker build -t hydranet -f Dockerfile ._
This should match the environment exactly and produce no error

**Comment by ghost** [comment]
ok thanks let me try . I am not familiar with docker

**Comment by ghost** [comment]
Hey while inferencing I am getting this result 
![image](https://user-images.githubusercontent.com/19353524/161786869-a5c1529b-89a9-4d30-b80f-5ec3feb11f29.png)
Is there any function that will convert it into sql string

**Comment by lyuqin** [comment]
Please refer to
https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/wikisql_prediction.py#L76
https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/wikisql_prediction.py#L88

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/19353524/161945457-132ed8e6-2ce1-4c5b-8080-7a4db2d19cad.png)
after exploring these methods got these result.But still not converting it into sql query or Giving answer to the question.
then I tried out evaluator file. got this random jargons as predicted query.
![image](https://user-images.githubusercontent.com/19353524/161946168-66ca8408-f8cd-44ee-98bc-8ee92941fc57.png)

**Comment by lyuqin** [comment]
> after exploring these methods got these result

The dictionary format is expected output of predict_SQL. It's in the same format as defined in WikiSQL for the sql label, and the two outputs exactly match the labels of the first two samples of test set.

> then I tried out evaluator file

As explained in readme, you can get official number from the output file by running the official evaluation script ([evaluate.py](https://github.com/salesforce/WikiSQL/blob/master/evaluate.py) in WikiSQL repo):
_Run WikiSQL evaluation script to get official numbers: cd WikiSQL && python evaluate.py data/test.jsonl data/test.db ../output/test_out.jsonl_
where test_out.jsonl is obtained by running wikisql_prediction.py and contains outputs from predict_SQL.  Moreover, you can find in their script the way to get SQL query for excecution from the dictionary format:
https://github.com/salesforce/WikiSQL/blob/0af869a830033f89a026b6c748879e04e1b0e2fc/evaluate.py#L25

Note that the evaluator.py file you ran is from HydraNet repo, and is only for evaluation during training. Its code under https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/evaluator.py#L101
is for unit test of the evaluation module. It randomly initiates a new model and hence produces random outputs.

**Comment by ghost** [comment]
Thanks finally got final predictions
