### ISSUE TITLE
RuntimeError: unexpected EOF, expected 3539973 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by yaoyiyao-yao** [lyuqin/HydraNet-WikiSQL#2]
Hi!
After I downloaded the model and want to evaluate , something error.
The details are as follows:
(python37) guest05@oem-04:~/yaoProjects/HydraNet-WikiSQL$ python wikisql_prediction.py 
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
5000
10000
15000
data/wikitest.jsonl loaded. Data shapes:
input_ids (101072, 96)
input_mask (101072, 96)
segment_ids (101072, 96)
num of samples: 15878
Traceback (most recent call last):
  File "/home/guest05/anaconda3/envs/python37/lib/python3.7/site-packages/transformers/modeling_utils.py", line 415, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/home/guest05/anaconda3/envs/python37/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/guest05/anaconda3/envs/python37/lib/python3.7/site-packages/torch/serialization.py", line 779, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 3539973 more bytes. The file might be corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wikisql_prediction.py", line 64, in <module>
    model = create_model(config, is_train=False)
  File "/home/guest05/yaoProjects/HydraNet-WikiSQL/modeling/model_factory.py", line 6, in create_model
    return HydraTorch(config)
  File "/home/guest05/yaoProjects/HydraNet-WikiSQL/modeling/torch_model.py", line 12, in __init__
    self.model = HydraNet(config)
  File "/home/guest05/yaoProjects/HydraNet-WikiSQL/modeling/torch_model.py", line 84, in __init__
    self.base_model = utils.create_base_model(config)
  File "/home/guest05/yaoProjects/HydraNet-WikiSQL/utils.py", line 36, in create_base_model
    return transformers.RobertaModel.from_pretrained(weights_name)
  File "/home/guest05/anaconda3/envs/python37/lib/python3.7/site-packages/transformers/modeling_utils.py", line 417, in from_pretrained
    raise OSError("Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
malloc(): unsorted double linked list corrupted
已放弃 (核心已转储)

Can you give me some suggestions?Thank you very much.

**Comment by lyuqin** [comment]
Can you double check the version: PyTorch==1.3.1, transformers==2.3.0 ? The exception is in loading models, which is Huggingface API (i.e., transformers)

**Comment by yaoyiyao-yao** [comment]
Thank you for your quick response!
I'm sure the version is PyTorch==1.3.1, transformers==2.3.0. Could you please show me the NVIDIA driver version and cuda version of your linux system? I guess there may be something wrong with the system.

**Comment by lyuqin** [comment]
I used Windows system and I don't think it's related to CUDA. Can you refer to this: https://github.com/huggingface/transformers/issues/1491

**Comment by yaoyiyao-yao** [comment]
After downing the "roberta-large"model from https://huggingface.co/roberta-large/tree/main and modifying the path in utils.py,the problem is solved.
